# Generated by Django 4.0.6 on 2022-08-09 15:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0009_walk_notes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='base',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='base',
            unique_together={('id', 'name')},
        ),
    ]
