# Generated by Django 4.0.6 on 2022-08-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0010_alter_base_managers_alter_base_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paw_platoon_app.walker'),
        ),
    ]
