# Generated by Django 4.0.6 on 2022-08-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0012_remove_walk_pet_walk_pets_alter_appuser_walker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='pets',
            field=models.ManyToManyField(to='paw_platoon_app.pet'),
        ),
    ]
