# Generated by Django 4.0.6 on 2022-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0014_walk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='walk',
            name='walk_length',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
