# Generated by Django 4.0.6 on 2022-08-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0015_alter_walk_date_alter_walk_walk_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
