# Generated by Django 4.0.6 on 2022-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0016_walk_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='pets',
            field=models.ManyToManyField(related_name='walks', to='paw_platoon_app.pet'),
        ),
    ]
