# Generated by Django 4.0.6 on 2022-08-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0017_alter_walk_pets'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='base',
            managers=[
            ],
        ),
    ]
