# Generated by Django 4.0.6 on 2022-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0019_walk_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.CharField(default='$25', max_length=255),
        ),
    ]
