# Generated by Django 4.0.6 on 2022-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0021_alter_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='79606', max_length=5),
        ),
    ]
